Решение задачи 771 Jewels and Stones. Пока еще на leetcode не проверял.
inajmudinov/Programming-challenges pull request #3
Opened 2020-04-18 15:02 UTC by inajmudinov

2020-04-18 17:48 UTC, vitkarpov requested changes
Давай оформим по шаблону для LeetCode, в классе. Чтобы тебе было удобнее тестировать прямо в шаблоне LeetCode, запуская из консоли как ты привык, при этом решение работало и на LeetCode при сдаче, можно это делать вот так:

```py
import sys

class Solution:
  def numJewelsInStones(self, J: str, S: str) -> int:
    # здесь твой код

# здесь напишем все тесты
def run_tests():
  # создаём объект экземпляр Solution (совсем простенькое ООП)
  sol = Solution()
  # печатаем тесты, вызываю метод этого объекта
  print(sol.numJewelsInStones("aA", "aAAbbbb"))
  print(sol.numJewelsInStones("aA", "bb"))

# вот это запустится только если будешь запускать скрипт из консоли
# $ python 771 Jewels and Stones.py
# а когда этот код будет запускать LeetCode, то выполняться не будет, что нам и нужно
if sys.stdin.isatty():
  run_tests()
```

Попробуй этот код, вставив только тело самой функции с решением предварительно. Он должен запускать тесты когда дёргаешь скрипт из консоли и в то же время сдаваться на LeetCode (твои принты будут игнорироваться).

2020-04-19 05:35 UTC, vitkarpov commented on 771 Jewels and Stones.py
> +  # создаём объект экземпляр Solution (совсем простенькое ООП)
Комменты были для тебя. Можешь удалить.

2020-04-19 05:35 UTC, vitkarpov commented on 771 Jewels and Stones.py
> +                    count += 1
Надо оценить сложность. Писал в личку где про это посмотреть. У тебя есть две строки, пусть их длины `N` и `M`. Сколько в худшем случае нужно сделать элементарных операций, какой верхний предел?

2020-04-19 05:38 UTC, inajmudinov commented on 771 Jewels and Stones.py
> +  # создаём объект экземпляр Solution (совсем простенькое ООП)
Пускай комменты останутся, для меня они как конспект лекций.

2020-04-19 05:39 UTC, inajmudinov commented on 771 Jewels and Stones.py
> +                    count += 1
Сейчас материал посмотрю и потом отвечу на твои вопросы.

2020-04-19 05:57 UTC, inajmudinov commented on 771 Jewels and Stones.py
> +                    count += 1
Верхний предел будет та строка у которой больше всего элементов.

2020-04-19 05:58 UTC, inajmudinov commented on 771 Jewels and Stones.py
> +                    count += 1
В худшем случае нужно будет сверят каждые элементы обоих массивов.

2020-04-19 06:11 UTC, inajmudinov commented on 771 Jewels and Stones.py
> +                    count += 1
На каждую итерацию первого цикла я прохожусь по всем элементам второго массива.

2020-04-19 06:21 UTC, vitkarpov commented on 771 Jewels and Stones.py
> +                    count += 1
Отлично! На этом месте интервьюер спросит тебя «можно ли улучшить сложность?». Если такой вопрос задают, скорее всего ответ — да :-)

2020-04-19 06:24 UTC, vitkarpov commented on 771 Jewels and Stones.py
> +                    count += 1
Подумай вот над чем. Для каждого символа из первой строки ты хочешь узнать есть ли она во второй строке. Вместо того, чтобы бегать по ней каждый раз — можно один раз загнать в `set` или `dict` и в цикле обращаться к нему.

Вопросы:

- что такое set и dict в питоне, в чем разница?
- какая сложность на запись и чтение в set и dict
- какая будет сложность в этой задаче если воспользоваться set или dict

2020-04-19 06:25 UTC, inajmudinov commented on 771 Jewels and Stones.py
> +                    count += 1
Встречный вопрос интервьюеру. На сортировку массива разве мы не теряем время ?

2020-04-19 06:26 UTC, vitkarpov commented on 771 Jewels and Stones.py
> +                    count += 1
Теряем. Не понятно к чему вопрос — здесь нет никакой сортировки :-)

2020-04-19 06:27 UTC, vitkarpov commented on 771 Jewels and Stones.py
> +                    count += 1
Уточни, пожалуйста, про что ты.

2020-04-19 06:28 UTC, vitkarpov commented on 771 Jewels and Stones.py
> +                    count += 1
Точнее не так, неявная сортировка есть если ты будешь пользоваться set. Дополнительный вопрос тогда «какая сложность создания set из массива».

2020-04-19 06:29 UTC, inajmudinov commented on 771 Jewels and Stones.py
> +                    count += 1
Этот вопрос относительно бинарного поиска, то есть передпоследней темы.

2020-04-19 06:33 UTC, vitkarpov commented on 771 Jewels and Stones.py
> +                    count += 1
> Этот вопрос относительно бинарного поиска, то есть передпоследней темы.

На то, чтобы отсортировать массив нужно потратить `N * log N` времени. Я говорил в видео, что если у вас K запросов на поиск, то выгоднее сперва потратить время на сортировку, а потом пулять K бинарных поисков — и получится сложность `N * log N + K * log N = (N + K) * log N`, что выгоднее чем `N^2`. Т.е. здесь конечно трейд-офф. Если надо найти один элемент, может и не нужен никакой бинарный поиск.

2020-04-22 07:49 UTC, vitkarpov approved these changes
🥇 

Огонь. Теперь работает за O(len(S) + len(J)). Не забываем, что на создание сета тоже время тратится O(len(J)), но это одно слагаемое теперь, а не множитель.

2020-04-22 14:24 UTC, inajmudinov commented
Отлично ! 👍👍👍

2020-04-22 14:33 UTC, merged