1108 Defang IP address
inajmudinov/Programming-challenges pull request #4
Opened 2020-04-23 05:00 UTC by inajmudinov

2020-04-23 05:02 UTC, vitkarpov requested changes
Этот вариант решения — 👌 , а теперь надо реализовать следующий.

2020-04-23 05:02 UTC, vitkarpov commented on 1108 defang ip addr.py
> +        return(address.replace(".", "[.]"))
Отлично, это работает 👍 
Теперь нужно сделать то же самое, только без использования replace. Суть этой задачки показать, что кандидат понимает как работает replace.

2020-04-23 05:03 UTC, inajmudinov commented on 1108 defang ip addr.py
> +        return(address.replace(".", "[.]"))
Ок, понял.

2020-04-24 03:26 UTC, vitkarpov approved these changes
Excellent! 🥇 

Момент, который стоит отложить себе, но мы подробнее вернёмся к нему в будущем. Строки в питоне immutable, это значит что при сложении `a += i` постоянно создаются новые строки и  из-за этого сложность из `O(n)` (просто чтобы пробежаться по строке) превращается в `O(n^2)` (пробежаться * скопировать).

Подробнее о проблеме можно почитать здесь — https://stackoverflow.com/questions/3055477/how-slow-is-pythons-string-concatenation-vs-str-join/3055541

Пока с этим делать ничего не будем, т.к. это easy задачи с маленьким размером входа, потом вернёмся к этому.

2020-04-24 03:59 UTC, inajmudinov commented
Большое спасибо за отзыв !

2020-04-24 04:14 UTC, merged